#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys
reload(sys)
sys.setdefaultencoding('utf-8')

from xpinyin import Pinyin
p = Pinyin()
#srccodec = sys.stdin.encoding or sys.getdefaultencoding()
srccodec = 'utf-8'
full = False

if len(sys.argv)>1 and sys.argv[1]=='-f':
  full = True

while True:
  line = sys.stdin.readline()
  if not line: break
  line = line.strip()
  src = unicode(line, srccodec)
  if full:
    print p.get_pinyin(src)
  else:
    for c in src:
      sys.stdout.write(p.get_initials(c))
    print 

