#!/bin/bash

while getopts "f" opt; do
case $opt in
  f)
  FULL="-f"
  ;;
  -)
  break;;
  \?)
  echo 'usage: lspy [-f] [pinyin]' >&2
  exit 1
  ;;
esac
done

shift $(($OPTIND - 1))

if [[ -n "$1" ]]; then
  FILE=$1
else
  FILE="*"
fi
IFS="
"
ls -1 | chinese2pinyin -o $FULL | (
  while read -r line
  do
    read -r pinyin
    [[ "$pinyin" == $FILE ]] && {
      echo $line
    }
  done
)

