#!/bin/bash

while getopts "f" opt; do
case $opt in
f)
  FULL="-f"
  ;;
-)
  break;;
\?)
  echo 'usage: lspy [-f] [pinyin]' >&2
  exit 1
  ;;
esac
done

shift $(($OPTIND - 1))

[[ -n "$1" ]] && FILE=$1 || FILE="*"

IFS="
"
ls -1 | chinese2pinyin -o $FULL | (
  while read -r line; do
    read -r pinyin
    [[ "$pinyin" == $FILE ]] && echo $line
  done
)

